import { QUALITY_REQUIRED_ARTIFACT_INSPECTION_CONTRACT, inspectDocsHonesty, inspectQualityRequiredArtifacts } from "./quality-radar.ts";
import { REPO_PATH_INSPECTION_CONTRACT, REPO_PATH_PRESENCE_CONTRACT, REPO_SCAN_CONTRACT, inspectRepoPathPresence, repoScanOptions } from "./repo-scan.ts";
import { SYNC_OBSERVATION_CONTRACT } from "./sync.ts";
import { CLAUDE_SYNC_INSPECTION_CONTRACT, MEMORY_REGISTRY_APPEND_CONTRACT, MEMORY_REGISTRY_SCAN_CONTRACT } from "./memory.ts";
import { MCP_FIXTURE_INSPECTION_CONTRACT } from "./mcp-dry-run.ts";
import { PANEL_READ_CONTRACT } from "../panel-server.ts";
import { RUNTIME_OBSERVATION_CONTRACT, RUNTIME_PROJECT_ASSET_CONTRACT, inspectRuntimeProjectAssets } from "./runtime.ts";
import { WORKFLOW_INSPECTION_CONTRACT, inspectWorkflowContracts } from "./workflow-contract.ts";
import { EXTERNAL_SKILL_REFRESH_INSPECTION_CONTRACT, I18N_ARTIFACT_INSPECTION_CONTRACT, N8N_CLI_OBSERVATION_CONTRACT, OPPORTUNITY_RADAR_INSPECTION_CONTRACT, SMART_SUGGESTION_INSPECTION_CONTRACT, WORKER_ENTRYPOINT_INSPECTION_CONTRACT, inspectExternalSkillsDryRun, inspectI18n, inspectOpportunityRadar } from "./operations.ts";
import { STATE_FILE_IO_CONTRACT } from "./state-file.ts";
import { DATABASE_PATH_INSPECTION_CONTRACT, DATABASE_SCHEMA_EXECUTION_CONTRACT, KERNEL_BOOTSTRAP_CONTRACT, inspectDatabasePath, inspectDatabaseSchema } from "./db.ts";
import { CONTRACT_TEXT_READ_CONTRACT, createContractTextReader } from "./contract-text.ts";
import { CLI_COMMAND_RECORD_CONTRACT } from "./cli-command.ts";
import { CLI_FINALIZATION_CONTRACT } from "./cli-finalization.ts";
import { CLI_OUTPUT_CONTRACT } from "./cli-output.ts";
import { DECISION_RECORD_CONTRACT } from "./decision-engine.ts";
import { REFERENCE_REFRESH_WRITE_CONTRACT } from "./reference-radar.ts";
import { INTERACTIVE_MISTAKE_CONTRACT } from "./interactive-memory.ts";
import { PUBLIC_READINESS_INSPECTION_CONTRACT, inspectPublicReadiness } from "./public-readiness.ts";
import { ARCHITECTURE_PATH_INSPECTION_CONTRACT, CLAUDE_SKILL_INSPECTION_CONTRACT, inspectArchitecture } from "./repo-inspection.ts";
import { DASHBOARD_GENERATION_CONTRACT } from "./dashboard.ts";
import { LEDGER_APPEND_CONTRACT } from "./ledger.ts";
import { LEDGER_REPAIR_WRITE_CONTRACT, LEDGER_SAFETY_SCAN_CONTRACT } from "./ledger-safety.ts";
import { LATEST_EVIDENCE_CONTRACT, PUBLIC_EVIDENCE_WRITE_CONTRACT, RAW_EVIDENCE_WRITE_CONTRACT } from "./evidence.ts";
import { EVIDENCE_EXCHANGE_CONTRACT, EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT, EVIDENCE_EXCHANGE_FILE_HANDLE_CAPABILITY, EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY, EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY } from "./evidence-exchange.ts";
import { ACTION_PLAN_USER_INPUT_CONTRACT, ARCHIVE_INVENTORY_CONTRACT, N8N_IMPORT_INSPECTION_CONTRACT, PLAN_SOURCE_TRUTH_CONTRACT } from "./action-plans.ts";

export const DRIFT_TEXT_READ_CONTRACT = CONTRACT_TEXT_READ_CONTRACT;

function createDriftTextContext(options = {}) {
  return createContractTextReader(options);
}

function parseJsonText(text) {
  try {
    return JSON.parse(text);
  } catch {
    return {};
  }
}

function majorVersion(value) {
  const parts = String(value || "").replace(/^v/i, "").split(".").map((part) => Number(part));
  if (!Number.isInteger(parts[0])) return null;
  return parts[0] === 0 && Number.isInteger(parts[1]) ? parts[1] : parts[0];
}

export function inspectVersionContract(input = {}) {
  const textContext = input.textContext || createDriftTextContext(input);
  const packageVersion = input.packageVersion ?? parseJsonText(textContext.read("package.json")).version;
  const manifestVersion = input.manifestVersion ?? parseJsonText(textContext.read("manifest.json")).version;
  const readmeText = input.readmeText ?? textContext.read("README.md");
  const packageMajor = majorVersion(packageVersion);
  const manifestMajor = majorVersion(manifestVersion);
  const textRead = textContext.summary();
  const checks = [
    { name: "Package version declares a major session version", ok: packageMajor !== null, evidence: "package.json" },
    { name: "Manifest version declares a major session version", ok: manifestMajor !== null, evidence: "manifest.json" },
    { name: "Package and manifest major version agree", ok: packageMajor !== null && packageMajor === manifestMajor, evidence: "package.json/manifest.json" },
    { name: "README current status agrees with package major version", ok: packageMajor !== null && new RegExp(`\\bv${packageMajor}\\b`, "i").test(readmeText), evidence: "README.md" },
    { name: "Version contract source reads are bounded and complete", ok: textRead.scan_complete, evidence: "package.json/manifest.json/README.md" }
  ];
  const failures = checks.filter((check) => !check.ok);
  return {
    status: failures.length === 0 ? "safe_to_execute" : "manual_verification_required",
    package_version: packageVersion || null,
    manifest_version: manifestVersion || null,
    scan_complete: textRead.scan_complete,
    blockers: textRead.blockers,
    text_read: textRead,
    checks,
    failures
  };
}

export function inspectDrift(quick = false, options = {}) {
  const bounded = repoScanOptions(options);
  const textContext = createDriftTextContext(bounded);
  const readText = (relativePath) => textContext.read(relativePath);
  const exists = (relativePath) => textContext.exists(relativePath);
  const versionContract = inspectVersionContract({ textContext });
  const workflowContract = inspectWorkflowContracts(bounded);
  const publicReadiness = inspectPublicReadiness({ ...bounded, workflowContract });
  const docsHonesty = inspectDocsHonesty(bounded);
  const readme = readText("README.md");
  const positioning = readText("docs/product/positioning.md");
  const overview = readText("control/overview/index.html");
  const cliDocs = readText("docs/CLI.md");
  const packageJson = readText("package.json");
  const architecture = readText("docs/ARCHITECTURE.md");
  const gitignore = readText(".gitignore");
  const mcpDocs = readText("docs/MCP_INSTALLER.md");
  const evidenceExchangeDocs = readText("docs/EVIDENCE_EXCHANGE.md");
  const workerDocs = readText("docs/WORKER.md");
  const adminDocs = readText("docs/ADMIN.md");
  const referenceRadarDocs = readText("docs/evidence/reference-radar.md");
  const decisionEngineDocs = readText("docs/DECISION_ENGINE.md");
  const memoryDocs = readText("docs/MEMORY.md");
  const n8nDocs = readText("docs/recipes/n8n-background.md");
  const databaseSchema = inspectDatabaseSchema({ projectRoot: bounded.projectRoot });
  const databasePath = inspectDatabasePath({ projectRoot: bounded.projectRoot });
  const architectureInspection = inspectArchitecture(bounded);
  const i18nInspection = inspectI18n(bounded);
  const externalSkillInspection = inspectExternalSkillsDryRun(bounded);
  const opportunityRadar = inspectOpportunityRadar(bounded);
  const runtimeProjectAssets = inspectRuntimeProjectAssets(bounded);
  const qualityRequiredArtifacts = inspectQualityRequiredArtifacts(bounded);
  const cliPathPresence = inspectRepoPathPresence("src/cli.ts", { ...bounded, expectedKind: "file" });
  const checks = [
    { name: "README exists", ok: exists("README.md"), evidence: "README.md" },
    { name: "Positioning doc exists", ok: exists("docs/product/positioning.md"), evidence: "docs/product/positioning.md" },
    { name: "Core positioning agrees across README, positioning, and dashboard", ok: [readme, positioning, overview].every((text) => text.includes("Agent does the work. Pala OS verifies the work.")), evidence: "README.md/docs/product/positioning.md/control/overview/index.html" },
    { name: "Command map has operator flow", ok: readText("docs/cli/command-map.md").includes("Before coding") && readText("docs/cli/command-map.md").includes("While coding") && readText("docs/cli/command-map.md").includes("After coding"), evidence: "docs/cli/command-map.md" },
    { name: "Strict CLI contract agrees with package script", ok: cliDocs.includes("npm run verify") && cliDocs.includes("--strict") && packageJson.includes("./src/cli.ts verify --strict"), evidence: "docs/CLI.md/package.json" },
    { name: "Dashboard read-only API and bounded route controls are documented and generated", ok: architecture.includes("/api/route/<route>") && architecture.includes("accepts writes") && overview.includes("id=\"route-filter\""), evidence: "docs/ARCHITECTURE.md/control/overview/index.html" },
    { name: "Dashboard route generation is fixed, contained, and atomic", ok: DASHBOARD_GENERATION_CONTRACT.policy === "bounded_fixed_project_contained_atomic_dashboard_generation" && DASHBOARD_GENERATION_CONTRACT.max_file_bytes === 1_000_000 && DASHBOARD_GENERATION_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && DASHBOARD_GENERATION_CONTRACT.concurrent_directory_creation_policy === "rechecked_eexist_tolerant" && DASHBOARD_GENERATION_CONTRACT.concurrent_generation_policy === "rechecked_transient_atomic_replace_retry" && DASHBOARD_GENERATION_CONTRACT.max_atomic_replace_attempts === 20 && DASHBOARD_GENERATION_CONTRACT.temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match_before_each_replace_attempt" && DASHBOARD_GENERATION_CONTRACT.identity_safe_temp_cleanup === true && DASHBOARD_GENERATION_CONTRACT.atomic_replace === true && DASHBOARD_GENERATION_CONTRACT.payload_exposed === false && cliDocs.includes("bounded_fixed_project_contained_atomic_dashboard_generation") && cliDocs.includes("rechecked_eexist_tolerant") && cliDocs.includes("rechecked_transient_atomic_replace_retry") && cliDocs.includes("write_handle_and_temporary_path_dev_ino_match_before_each_replace_attempt") && architecture.includes("Dashboard route generation") && readText("src/lib/dashboard.ts").includes("generateDashboardRoutes") && readText("src/lib/dashboard.ts").includes("TRANSIENT_ATOMIC_REPLACE_ERROR_CODES") && readText("src/lib/dashboard.ts").includes("unlinkIfSameFileIdentity") && readText("src/lib/dashboard.ts").includes("fs.renameSync"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/dashboard.ts" },
    { name: "Runtime persistence ignore contract is present", ok: [".pala/db/*.sqlite", ".pala/evidence/raw/", ".pala/state/", ".pala/ledger/", ".pala/archive/"].every((pattern) => gitignore.includes(pattern)), evidence: ".gitignore" },
    { name: "MCP docs expose check and ownership-safe remove contracts", ok: mcpDocs.includes("setup --check --all") && mcpDocs.includes("setup --remove --dry-run --all") && mcpDocs.includes("ownership conflict"), evidence: "docs/MCP_INSTALLER.md" },
    { name: "MCP fixture inspection is bounded and payload-free", ok: MCP_FIXTURE_INSPECTION_CONTRACT.policy === "realpath_contained_single_handle_max_1mb_payload_free" && MCP_FIXTURE_INSPECTION_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && MCP_FIXTURE_INSPECTION_CONTRACT.max_file_bytes === 1_000_000 && MCP_FIXTURE_INSPECTION_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && MCP_FIXTURE_INSPECTION_CONTRACT.close_failure_blocker === "fixture_file_close_failed" && MCP_FIXTURE_INSPECTION_CONTRACT.payload_exposed === false && MCP_FIXTURE_INSPECTION_CONTRACT.payload_exposed_on_failure === false && MCP_FIXTURE_INSPECTION_CONTRACT.writes_allowed === false && mcpDocs.includes("fixture_file_close_failed") && mcpDocs.includes("structured_fail_closed_no_throw") && architecture.includes("MCP fixture inspection") && architecture.includes("fixture_file_close_failed") && readText("src/lib/mcp-dry-run.ts").includes("MCP_FIXTURE_INSPECTION_CONTRACT.close_failure_blocker") && !readText("src/lib/mcp-dry-run.ts").includes("fs.existsSync"), evidence: "docs/MCP_INSTALLER.md/docs/ARCHITECTURE.md/src/lib/mcp-dry-run.ts" },
    { name: "Panel file serving is loopback-only and bounded", ok: PANEL_READ_CONTRACT.policy === "loopback_read_only_realpath_contained_single_handle_max_bytes" && PANEL_READ_CONTRACT.allowed_hosts.length === 2 && PANEL_READ_CONTRACT.max_state_file_bytes === 1_000_000 && PANEL_READ_CONTRACT.max_static_file_bytes === 1_000_000 && PANEL_READ_CONTRACT.max_route_response_bytes === 1_000_000 && PANEL_READ_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && PANEL_READ_CONTRACT.close_failure_reason === "file_close_failed" && PANEL_READ_CONTRACT.database_close_failure_reason === "route_database_close_failed" && PANEL_READ_CONTRACT.database_post_read_path_recheck === true && PANEL_READ_CONTRACT.database_path_change_reason === "route_database_path_changed_after_read" && PANEL_READ_CONTRACT.route_response_limit_reason === "route_response_exceeds_byte_limit" && PANEL_READ_CONTRACT.state_head_validation_policy === "same_validation_status_as_get_without_body" && PANEL_READ_CONTRACT.static_head_validation_policy === "same_read_status_as_get_without_body" && PANEL_READ_CONTRACT.startup_failure_policy === "structured_payload_free_without_raw_error" && PANEL_READ_CONTRACT.startup_failure_error === "panel_start_failed" && PANEL_READ_CONTRACT.raw_startup_error_exposed === false && PANEL_READ_CONTRACT.payload_exposed_on_failure === false && PANEL_READ_CONTRACT.writes_allowed === false && architecture.includes("loopback_read_only_realpath_contained_single_handle_max_bytes") && architecture.includes("file_close_failed") && architecture.includes("panel_start_failed") && architecture.includes("route_database_close_failed") && architecture.includes("route_database_path_changed_after_read") && architecture.includes("route_response_exceeds_byte_limit") && architecture.includes("State `HEAD`") && architecture.includes("Static `HEAD`") && cliDocs.includes("unsafe or oversized panel files") && cliDocs.includes("file_close_failed") && cliDocs.includes("panel_start_failed") && cliDocs.includes("route_database_close_failed") && cliDocs.includes("route_database_path_changed_after_read") && cliDocs.includes("route_response_exceeds_byte_limit") && cliDocs.includes("same_validation_status_as_get_without_body") && cliDocs.includes("same_read_status_as_get_without_body") && readText("src/panel-server.ts").includes("panelStartupFailureResult") && readText("src/panel-server.ts").includes("pathHasSymlinkAtOrBelowRoot") && readText("src/panel-server.ts").includes("PANEL_READ_CONTRACT.database_close_failure_reason") && readText("src/panel-server.ts").includes("PANEL_READ_CONTRACT.database_path_change_reason") && readText("src/panel-server.ts").includes("PANEL_READ_CONTRACT.route_response_limit_reason"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/panel-server.ts" },
    { name: "State JSON reads and refresh writes are bounded and atomic", ok: STATE_FILE_IO_CONTRACT.policy === "bounded_project_contained_single_handle_state_json_with_atomic_replace" && STATE_FILE_IO_CONTRACT.max_file_bytes === 1_000_000 && STATE_FILE_IO_CONTRACT.allowed_file_count === 5 && STATE_FILE_IO_CONTRACT.existence_probe_policy === "single_lstat_with_enoent_only_missing_truth" && STATE_FILE_IO_CONTRACT.concurrent_write_policy === "last_writer_wins_rechecked_transient_atomic_replace_retry" && STATE_FILE_IO_CONTRACT.max_atomic_replace_attempts === 20 && STATE_FILE_IO_CONTRACT.temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match_before_each_replace_attempt" && STATE_FILE_IO_CONTRACT.identity_safe_temp_cleanup === true && STATE_FILE_IO_CONTRACT.atomic_replace === true && STATE_FILE_IO_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && STATE_FILE_IO_CONTRACT.close_failure_blocker === "state_file_close_failed" && STATE_FILE_IO_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("bounded_project_contained_single_handle_state_json_with_atomic_replace") && cliDocs.includes("single_lstat_with_enoent_only_missing_truth") && cliDocs.includes("state_file_close_failed") && cliDocs.includes("last_writer_wins_rechecked_transient_atomic_replace_retry") && cliDocs.includes("write_handle_and_temporary_path_dev_ino_match_before_each_replace_attempt") && architecture.includes("atomic replace") && architecture.includes("reference-radar-state.json") && architecture.includes("state_file_close_failed") && readText("src/lib/state-refresh.ts").includes("writeBoundedStateJson") && readText("src/lib/reference-radar.ts").includes("writeBoundedStateJson") && readText("src/lib/state-file.ts").includes("STATE_FILE_IO_CONTRACT.close_failure_blocker") && readText("src/lib/state-file.ts").includes("TRANSIENT_ATOMIC_REPLACE_ERROR_CODES") && readText("src/lib/state-file.ts").includes("unlinkIfSameFileIdentity") && readText("src/cli.ts").includes("project_state_read") && !readText("src/lib/state-file.ts").includes("fs.existsSync"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/state-file.ts/src/lib/state-refresh.ts/src/lib/reference-radar.ts/src/cli.ts" },
    { name: "Database schema initialization is bounded and authorized", ok: DATABASE_SCHEMA_EXECUTION_CONTRACT.policy === "bounded_project_contained_single_handle_schema_with_authorized_sqlite_execution" && DATABASE_SCHEMA_EXECUTION_CONTRACT.authorizer_required === true && DATABASE_SCHEMA_EXECUTION_CONTRACT.attach_allowed === false && DATABASE_SCHEMA_EXECUTION_CONTRACT.load_extension_allowed === false && DATABASE_SCHEMA_EXECUTION_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && DATABASE_SCHEMA_EXECUTION_CONTRACT.close_failure_blocker === "database_schema_file_close_failed" && DATABASE_SCHEMA_EXECUTION_CONTRACT.payload_exposed_on_failure === false && databaseSchema.status === "safe_to_execute" && databaseSchema.single_file_handle_used === true && databaseSchema.payload_exposed === false && cliDocs.includes("bounded_project_contained_single_handle_schema_with_authorized_sqlite_execution") && cliDocs.includes("database_schema_file_close_failed") && architecture.includes("SQLite authorizer") && architecture.includes("database_schema_file_close_failed") && readText("src/lib/db.ts").includes("DATABASE_SCHEMA_EXECUTION_CONTRACT.close_failure_blocker") && readText("src/lib/db.ts").includes("executeDatabaseSchema"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/db.ts/.pala/schema/001_init.sql" },
    { name: "Database path observation is contained and payload-free", ok: DATABASE_PATH_INSPECTION_CONTRACT.policy === "fixed_project_contained_database_path_metadata_only" && DATABASE_PATH_INSPECTION_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && DATABASE_PATH_INSPECTION_CONTRACT.payload_exposed === false && DATABASE_PATH_INSPECTION_CONTRACT.writes_allowed === false && databasePath.status === "safe_to_execute" && databasePath.exists === true && databasePath.kind === "file" && databasePath.payload_exposed === false && cliDocs.includes("fixed_project_contained_database_path_metadata_only") && architecture.includes("Database path observation") && readText("src/lib/db.ts").includes("inspectDatabasePath") && !readText("src/lib/db.ts").includes("fs.existsSync"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/db.ts" },
    { name: "Kernel bootstrap is fixed, contained, and create-only", ok: KERNEL_BOOTSTRAP_CONTRACT.policy === "fixed_project_contained_create_only_kernel_bootstrap" && KERNEL_BOOTSTRAP_CONTRACT.directory_count === 12 && KERNEL_BOOTSTRAP_CONTRACT.initialized_file_count === 9 && KERNEL_BOOTSTRAP_CONTRACT.protected_file_count === 11 && KERNEL_BOOTSTRAP_CONTRACT.concurrent_directory_creation_policy === "rechecked_eexist_tolerant" && KERNEL_BOOTSTRAP_CONTRACT.atomic_create_link === true && KERNEL_BOOTSTRAP_CONTRACT.initialized_file_temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match" && KERNEL_BOOTSTRAP_CONTRACT.initialized_file_identity_safe_temp_cleanup === true && KERNEL_BOOTSTRAP_CONTRACT.initialized_file_post_publish_identity_policy === "temporary_and_initialized_file_dev_ino_match" && KERNEL_BOOTSTRAP_CONTRACT.existing_files_overwritten === false && cliDocs.includes("fixed_project_contained_create_only_kernel_bootstrap") && cliDocs.includes("rechecked_eexist_tolerant") && cliDocs.includes("write_handle_and_temporary_path_dev_ino_match") && cliDocs.includes("temporary_and_initialized_file_dev_ino_match") && architecture.includes("Kernel bootstrap") && readText("src/lib/db.ts").includes("bootstrapKernel") && readText("src/lib/db.ts").includes("unlinkIfSameFileIdentity") && readText("src/lib/db.ts").includes("sameFileIdentity") && !readText("src/lib/db.ts").includes("mkdirSync(dir, { recursive: true })"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/db.ts" },
    { name: "CLI contract source reads are bounded and surfaced", ok: CONTRACT_TEXT_READ_CONTRACT.policy === "bounded_cached_contract_text_reads_with_shared_budget" && CONTRACT_TEXT_READ_CONTRACT.max_file_bytes === 2_000_000 && CONTRACT_TEXT_READ_CONTRACT.max_total_text_bytes === 20_000_000 && CONTRACT_TEXT_READ_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && CONTRACT_TEXT_READ_CONTRACT.payload_exposed === false && CONTRACT_TEXT_READ_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("CLI contract-source reads use the same cached bounded reader") && cliDocs.includes("repo_text_file_close_failed") && readText("src/cli.ts").includes("cli_text_read") && readText("src/lib/contract-text.ts").includes("REPO_SCAN_CONTRACT.metadata_failure_policy"), evidence: "docs/CLI.md/src/cli.ts/src/lib/contract-text.ts" },
    { name: "CLI final output and failure payload follow close truth", ok: CLI_OUTPUT_CONTRACT.policy === "close_database_before_stdout_json" && CLI_OUTPUT_CONTRACT.max_output_bytes === 5_000_000 && CLI_OUTPUT_CONTRACT.serialization_preflight_before_database_close === true && CLI_OUTPUT_CONTRACT.serialization_failure_error === "cli_output_blocked:serialization_failed" && CLI_OUTPUT_CONTRACT.output_byte_limit_error === "cli_output_blocked:output_exceeds_byte_limit" && CLI_OUTPUT_CONTRACT.unsafe_output_policy === "payload_free_failure_json_after_database_close" && CLI_OUTPUT_CONTRACT.database_close_failure_error === "cli_output_blocked:database_close_failed" && CLI_OUTPUT_CONTRACT.top_level_failure_policy === "nonzero_without_raw_stack_or_pending_payload" && CLI_OUTPUT_CONTRACT.top_level_failure_error === "cli_top_level_failed" && CLI_OUTPUT_CONTRACT.top_level_failure_output_policy === "fixed_payload_free_json_best_effort" && CLI_OUTPUT_CONTRACT.command_failure_policy === "structured_payload_free_without_stack" && CLI_OUTPUT_CONTRACT.command_failure_error === "cli_command_failed" && CLI_OUTPUT_CONTRACT.unknown_command_policy === "structured_payload_free_without_raw_command" && CLI_OUTPUT_CONTRACT.unknown_command_error === "unknown_command" && CLI_OUTPUT_CONTRACT.raw_unknown_command_exposed === false && CLI_OUTPUT_CONTRACT.raw_error_exposed === false && CLI_OUTPUT_CONTRACT.stack_exposed === false && CLI_OUTPUT_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("close_database_before_stdout_json") && cliDocs.includes("payload_free_failure_json_after_database_close") && cliDocs.includes("fixed_payload_free_json_best_effort") && cliDocs.includes("structured_payload_free_without_stack") && cliDocs.includes("structured_payload_free_without_raw_command") && architecture.includes("CLI final output") && architecture.includes("Unknown top-level commands") && readText("src/cli.ts").includes("unknownCliCommandResult(REQUIRED_COMMANDS)") && readText("src/cli.ts").includes("\"command-unknown\"") && readText("src/cli.ts").includes("writeCliOutputAfterDatabaseClose(db, output)") && readText("src/cli.ts").includes("writeTopLevelCliFailure(error)") && readText("src/cli.ts").includes("cliFailureResult(error)") && !readText("src/cli.ts").includes("process.stdout." + "write") && !readText("src/cli.ts").includes("error." + "stack") && !readText("src/cli.ts").includes("Unknown command:" + " ${name}") && readText("src/lib/cli-output.ts").includes("CLI_OUTPUT_CONTRACT.database_close_failure_error") && readText("src/lib/cli-output.ts").includes("CLI_OUTPUT_CONTRACT.output_byte_limit_error") && readText("src/lib/cli-output.ts").includes("CLI_OUTPUT_CONTRACT.top_level_failure_error") && readText("src/lib/cli-output.ts").includes("CLI_OUTPUT_CONTRACT.command_failure_error") && readText("src/lib/cli-output.ts").includes("CLI_OUTPUT_CONTRACT.unknown_command_error"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/cli.ts/src/lib/cli-output.ts" },
    { name: "CLI finalization writes expose explicit outcome truth", ok: CLI_FINALIZATION_CONTRACT.policy === "explicit_outcome_cli_finalization_before_database_close" && CLI_FINALIZATION_CONTRACT.required_steps.length === 5 && CLI_FINALIZATION_CONTRACT.step_outcomes.join(",") === "not_attempted,confirmed,unknown_after_attempt" && CLI_FINALIZATION_CONTRACT.write_failure_policy === "manual_verification_required_exit_1" && CLI_FINALIZATION_CONTRACT.dependent_step_policy === "not_attempted_when_prerequisite_unconfirmed" && CLI_FINALIZATION_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("explicit_outcome_cli_finalization_before_database_close") && cliDocs.includes("not_attempted_when_prerequisite_unconfirmed") && architecture.includes("CLI finalization") && readText("src/cli.ts").includes("finalizeCliCommand({") && readText("src/lib/cli-finalization.ts").includes("cli_ledger_append_outcome_unknown") && readText("src/lib/state-refresh.ts").includes("current_finalization"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/cli.ts/src/lib/cli-finalization.ts/src/lib/state-refresh.ts" },
    { name: "CLI command records are bounded and redacted before persistence", ok: CLI_COMMAND_RECORD_CONTRACT.policy === "bounded_redacted_cli_command_record" && CLI_COMMAND_RECORD_CONTRACT.max_argument_count === 100 && CLI_COMMAND_RECORD_CONTRACT.max_argument_bytes === 1_024 && CLI_COMMAND_RECORD_CONTRACT.max_command_bytes === 4_096 && CLI_COMMAND_RECORD_CONTRACT.raw_arguments_exposed === false && CLI_COMMAND_RECORD_CONTRACT.sensitive_argument_values_exposed === false && cliDocs.includes("bounded_redacted_cli_command_record") && architecture.includes("CLI command record") && readText("src/cli.ts").includes("buildCliCommandRecord(args)") && readText("src/cli.ts").includes("command_record: commandRecord") && !readText("src/cli.ts").includes("args." + "join(\" \")") && readText("src/lib/state-refresh.ts").includes("current_command_record"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/cli.ts/src/lib/cli-command.ts/src/lib/state-refresh.ts" },
    { name: "Decision records are bounded and redacted before persistence", ok: DECISION_RECORD_CONTRACT.policy === "bounded_redacted_decision_record_before_persistence" && DECISION_RECORD_CONTRACT.max_inputs_bytes === 100_000 && DECISION_RECORD_CONTRACT.max_metadata_bytes === 25_000 && DECISION_RECORD_CONTRACT.max_related_rule_count === 100 && DECISION_RECORD_CONTRACT.max_related_rule_id_bytes === 256 && DECISION_RECORD_CONTRACT.max_reason_bytes === 2_000 && DECISION_RECORD_CONTRACT.max_decision_type_bytes === 120 && DECISION_RECORD_CONTRACT.oversized_inputs_policy === "metadata_only_manual_verification_required" && DECISION_RECORD_CONTRACT.serialization_failure_policy === "metadata_only_manual_verification_required" && DECISION_RECORD_CONTRACT.unsafe_metadata_policy === "metadata_only_manual_verification_required" && DECISION_RECORD_CONTRACT.persistence_policy === "evidence_then_ledger_then_database_with_explicit_outcomes" && DECISION_RECORD_CONTRACT.persistence_step_outcomes.join(",") === "not_attempted,confirmed,unknown_after_attempt" && DECISION_RECORD_CONTRACT.persistence_failure_policy === "manual_verification_required_without_raw_error" && DECISION_RECORD_CONTRACT.persistence_pending_marker === true && DECISION_RECORD_CONTRACT.raw_inputs_exposed === false && DECISION_RECORD_CONTRACT.raw_metadata_exposed === false && DECISION_RECORD_CONTRACT.payload_exposed_on_failure === false && decisionEngineDocs.includes("bounded_redacted_decision_record_before_persistence") && decisionEngineDocs.includes("metadata_only_manual_verification_required") && decisionEngineDocs.includes("evidence_then_ledger_then_database_with_explicit_outcomes") && decisionEngineDocs.includes("25,000") && architecture.includes("Decision record persistence") && readText("src/lib/decision-engine.ts").includes("inputs_record: boundedInputs.record") && readText("src/lib/decision-engine.ts").includes("metadata_record: boundedMetadata.record") && readText("src/lib/decision-engine.ts").includes("boundedRedactedDecisionMetadata") && readText("src/lib/decision-engine.ts").includes("decision_database_insert_outcome_unknown") && readText("src/lib/decision-engine.ts").includes("DECISION_RECORD_CONTRACT.max_reason_bytes"), evidence: "docs/DECISION_ENGINE.md/docs/ARCHITECTURE.md/src/lib/decision-engine.ts" },
    { name: "Runtime command observations are bounded and raw-output-free", ok: RUNTIME_OBSERVATION_CONTRACT.policy === "bounded_fixed_command_process_metadata_with_redacted_first_line" && RUNTIME_OBSERVATION_CONTRACT.timeout_ms === 5000 && RUNTIME_OBSERVATION_CONTRACT.max_output_bytes === 64_000 && RUNTIME_OBSERVATION_CONTRACT.raw_output_exposed === false && cliDocs.includes("bounded_fixed_command_process_metadata_with_redacted_first_line") && architecture.includes("redacted first-line summary") && readText("src/lib/runtime.ts").includes("output_limit_exceeded"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/runtime.ts" },
    { name: "Runtime project asset paths are contained and payload-free", ok: RUNTIME_PROJECT_ASSET_CONTRACT.policy === "bounded_fixed_runtime_project_asset_path_metadata_scan" && RUNTIME_PROJECT_ASSET_CONTRACT.required_path_count === 5 && RUNTIME_PROJECT_ASSET_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && RUNTIME_PROJECT_ASSET_CONTRACT.payload_exposed === false && runtimeProjectAssets.status === "safe_to_execute" && runtimeProjectAssets.inspections.length === 5 && cliDocs.includes("bounded_fixed_runtime_project_asset_path_metadata_scan") && architecture.includes("Runtime project asset path inspection") && readText("src/lib/runtime.ts").includes("inspectRuntimeProjectAssets"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/runtime.ts/src/lib/repo-scan.ts" },
    { name: "Optional n8n CLI observation is bounded and raw-output-free", ok: N8N_CLI_OBSERVATION_CONTRACT.policy === "bounded_optional_n8n_version_metadata_with_redacted_first_line" && N8N_CLI_OBSERVATION_CONTRACT.windows_discovery_policy === "bounded_windows_where_n8n_cmd_presence_only" && N8N_CLI_OBSERVATION_CONTRACT.max_output_bytes === 16_000 && N8N_CLI_OBSERVATION_CONTRACT.raw_output_exposed === false && n8nDocs.includes("bounded_optional_n8n_version_metadata_with_redacted_first_line") && n8nDocs.includes("bounded_windows_where_n8n_cmd_presence_only") && architecture.includes("Optional n8n CLI availability") && readText("src/lib/operations.ts").includes("n8n_cli_discovery_timed_out"), evidence: "docs/CLI.md/docs/recipes/n8n-background.md/docs/ARCHITECTURE.md/src/lib/operations.ts" },
    { name: "CLAUDE sync dry-run is bounded and proposal-gated", ok: CLAUDE_SYNC_INSPECTION_CONTRACT.policy === "bounded_project_contained_single_handle_claude_md_dry_run" && CLAUDE_SYNC_INSPECTION_CONTRACT.max_file_bytes === 1_000_000 && CLAUDE_SYNC_INSPECTION_CONTRACT.payload_exposed === false && memoryDocs.includes("bounded_project_contained_single_handle_claude_md_dry_run") && memoryDocs.includes("proposal is blocked") && readText("src/lib/memory.ts").includes("readBoundedRepoText"), evidence: "docs/MEMORY.md/src/lib/memory.ts" },
    { name: "Workflow contract scan is bounded and payload-free", ok: WORKFLOW_INSPECTION_CONTRACT.policy === "bounded_project_contained_single_handle_workflow_contract_scan" && WORKFLOW_INSPECTION_CONTRACT.max_file_bytes === 1_000_000 && WORKFLOW_INSPECTION_CONTRACT.max_total_text_bytes === 2_000_000 && WORKFLOW_INSPECTION_CONTRACT.mutation_payload_exposed === false && cliDocs.includes("bounded_project_contained_single_handle_workflow_contract_scan") && architecture.includes("Workflow contract inspection") && readText("src/lib/workflow-contract.ts").includes("file_inspections"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/workflow-contract.ts" },
    { name: "Public readiness artifact inspection is bounded and payload-free", ok: PUBLIC_READINESS_INSPECTION_CONTRACT.policy === "bounded_required_public_artifact_single_handle_scan" && PUBLIC_READINESS_INSPECTION_CONTRACT.required_file_count === 30 && PUBLIC_READINESS_INSPECTION_CONTRACT.max_file_bytes === 2_000_000 && PUBLIC_READINESS_INSPECTION_CONTRACT.max_total_text_bytes === 20_000_000 && PUBLIC_READINESS_INSPECTION_CONTRACT.payload_exposed === false && PUBLIC_READINESS_INSPECTION_CONTRACT.writes_allowed === false && publicReadiness.status === "safe_to_execute" && publicReadiness.scan_complete === true && publicReadiness.payload_exposed === false && cliDocs.includes("bounded_required_public_artifact_single_handle_scan") && architecture.includes("Public-readiness artifact inspection") && readText("src/lib/public-readiness.ts").includes("artifact_inspections"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/public-readiness.ts" },
    { name: "Sanitized evidence exchange contract is documented and implemented", ok: evidenceExchangeDocs.includes("Never overwrites") && evidenceExchangeDocs.includes("Import is validation-only") && evidenceExchangeDocs.includes("never returns the payload") && evidenceExchangeDocs.includes("Schema version: `2`") && evidenceExchangeDocs.includes("decision_review") && evidenceExchangeDocs.includes("`exact_match_only`") && architecture.includes("/api/route/evidence-exchange") && exists("src/lib/evidence-exchange.ts"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence exchange export writes are contained and create-only", ok: EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.policy === "bounded_project_contained_atomic_create_only_evidence_export" && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.max_raw_file_bytes === 2_000_000 && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.parent_directory_creation_policy === "one_segment_at_a_time_with_path_recheck" && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.concurrent_parent_creation_policy === "rechecked_eexist_tolerant" && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.concurrent_publish_policy === "atomic_create_only_one_winner_existing_target_needs_approval" && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match" && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.identity_safe_temp_cleanup === true && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.post_publish_identity_policy === "temporary_and_target_dev_ino_match" && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.atomic_create_link === true && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.overwrite_allowed === false && EVIDENCE_EXCHANGE_EXPORT_WRITE_CONTRACT.payload_exposed_on_failure === false && evidenceExchangeDocs.includes("bounded_project_contained_atomic_create_only_evidence_export") && evidenceExchangeDocs.includes("atomic_create_only_one_winner_existing_target_needs_approval") && evidenceExchangeDocs.includes("write_handle_and_temporary_path_dev_ino_match") && evidenceExchangeDocs.includes("temporary_and_target_dev_ino_match") && architecture.includes("Evidence exchange export write") && readText("src/lib/evidence-exchange.ts").includes("writeEvidenceExportAtomic") && readText("src/lib/evidence-exchange.ts").includes("unlinkIfSameFileIdentity") && readText("src/lib/evidence-exchange.ts").includes("sameFileIdentity") && !readText("src/lib/evidence-exchange.ts").includes("fs.writeFileSync(resolved.fullPath"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Benchmark refresh queue contract is documented and implemented", ok: referenceRadarDocs.includes("benchmark-refresh --dry-run") && referenceRadarDocs.includes("stale_reasons") && architecture.includes("/api/route/benchmarks") && exists("src/lib/reference-radar.ts"), evidence: "docs/evidence/reference-radar.md/docs/ARCHITECTURE.md/src/lib/reference-radar.ts" },
    { name: "Reference refresh ledger append outcome is explicit", ok: REFERENCE_REFRESH_WRITE_CONTRACT.policy === "state_then_ledger_with_explicit_append_outcome" && REFERENCE_REFRESH_WRITE_CONTRACT.state_before_ledger === true && REFERENCE_REFRESH_WRITE_CONTRACT.ledger_outcome_policy === "not_attempted_confirmed_or_unknown_after_attempt" && REFERENCE_REFRESH_WRITE_CONTRACT.ledger_failure_blocker === "reference_refresh_ledger_write_outcome_unknown" && REFERENCE_REFRESH_WRITE_CONTRACT.payload_exposed_on_failure === false && referenceRadarDocs.includes("not_attempted_confirmed_or_unknown_after_attempt") && cliDocs.includes("unknown_after_attempt") && architecture.includes("Reference refresh write truth") && readText("src/lib/reference-radar.ts").includes("ledger_write_attempted: ledgerWriteAttempted") && readText("src/lib/reference-radar.ts").includes("ledger_write_outcome: ledgerWriteOutcome"), evidence: "docs/evidence/reference-radar.md/docs/CLI.md/docs/ARCHITECTURE.md/src/lib/reference-radar.ts" },
    { name: "Decision review queue contract is documented and implemented", ok: decisionEngineDocs.includes("decision-review --strict") && /latest reviewable decision per decision\s+type/.test(decisionEngineDocs) && architecture.includes("/api/route/decision-review") && exists("src/lib/decision-review.ts"), evidence: "docs/DECISION_ENGINE.md/docs/ARCHITECTURE.md/src/lib/decision-review.ts" },
    { name: "Decision review aging policy is documented and implemented", ok: ["Critical: 1 day", "High: 7 days", "Medium: 30 days", "review_age_exceeds_threshold"].every((item) => decisionEngineDocs.includes(item)) && exists("src/lib/decision-review.ts"), evidence: "docs/DECISION_ENGINE.md/src/lib/decision-review.ts" },
    { name: "Evidence exchange migration plan is documented and implemented", ok: evidenceExchangeDocs.includes("evidence migrate --dry-run --target") && evidenceExchangeDocs.includes("candidate payload is never returned") && evidenceExchangeDocs.includes("requires_source_project_reexport") && readText("src/lib/evidence-exchange.ts").includes("planEvidenceExchangeMigration"), evidence: "docs/EVIDENCE_EXCHANGE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence exchange migration capability is dashboard-visible without payloads or writes", ok: evidenceExchangeDocs.includes("migration capability") && evidenceExchangeDocs.includes("candidate payload") && architecture.includes("migration capability") && readText("src/lib/panel-data.ts").includes("migration_capability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/panel-data.ts" },
    { name: "Evidence migration readiness plan is documented and dashboard-visible", ok: EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY.policy === "validated_source_schema_migration_readiness_approval_plan" && EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY.mode === "read_only_approval_plan" && EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY.target_read_performed === false && EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY.candidate_validation_performed === false && EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY.candidate_payload_exposed === false && EVIDENCE_EXCHANGE_MIGRATION_READINESS_CAPABILITY.writes_allowed === false && evidenceExchangeDocs.includes("validated_source_schema_migration_readiness_approval_plan") && architecture.includes("migration-readiness capability") && readText("src/lib/evidence-exchange.ts").includes("planEvidenceExchangeMigrationReadiness") && readText("src/lib/panel-data.ts").includes("migration_readiness_capability") && !readText("src/cli.ts").includes("real_evidence_migration_requires_reviewed_" + "implementation"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts/src/cli.ts" },
    { name: "Stable evidence content digest is documented and implemented", ok: evidenceExchangeDocs.includes("canonical_without_generated_at") && evidenceExchangeDocs.includes("content_digest_sha256") && architecture.includes("stable content digest") && readText("src/lib/evidence-exchange.ts").includes("evidenceExchangeContentDigest"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence exchange change detector is documented and implemented", ok: evidenceExchangeDocs.includes("evidence compare --dry-run --target") && evidenceExchangeDocs.includes("digest_and_count_delta_only") && readText("src/lib/evidence-exchange.ts").includes("compareEvidenceExchangeTarget") && readText("src/cli.ts").includes("sub === \"compare\""), evidence: "docs/EVIDENCE_EXCHANGE.md/src/lib/evidence-exchange.ts/src/cli.ts" },
    { name: "Evidence exchange comparison capability is dashboard-visible without target reads", ok: evidenceExchangeDocs.includes("fixed comparison capability") && evidenceExchangeDocs.includes("comparison target") && evidenceExchangeDocs.includes("run a comparison") && architecture.includes("comparison capability") && readText("src/lib/panel-data.ts").includes("comparison_capability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/panel-data.ts" },
    { name: "Evidence content digest assertion is documented and implemented", ok: evidenceExchangeDocs.includes("evidence assert-content --content-digest") && evidenceExchangeDocs.includes("expected_sha256_only_no_file_read") && readText("src/lib/evidence-exchange.ts").includes("assertEvidenceExchangeContentDigest") && readText("src/cli.ts").includes("sub === \"assert-content\""), evidence: "docs/EVIDENCE_EXCHANGE.md/src/lib/evidence-exchange.ts/src/cli.ts" },
    { name: "Evidence content assertion capability is dashboard-visible without running assertions", ok: evidenceExchangeDocs.includes("assertion capability") && evidenceExchangeDocs.includes("does not run an assertion") && architecture.includes("assertion capability") && readText("src/lib/panel-data.ts").includes("assertion_capability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/panel-data.ts" },
    { name: "Evidence exchange collection truncation truth is documented and implemented", ok: evidenceExchangeDocs.includes("exact_counts_or_explicit_unknown") && evidenceExchangeDocs.includes("unknown_beyond_scan_limit") && architecture.includes("collection truncation") && readText("src/lib/evidence-exchange.ts").includes("collectionTruncation") && readText("src/lib/panel-data.ts").includes("collection_truncation"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence truncation metadata consistency validation is documented and implemented", ok: evidenceExchangeDocs.includes("validate_when_present") && evidenceExchangeDocs.includes("truncation_metadata_status") && readText("src/lib/evidence-exchange.ts").includes("validateCollectionTruncation"), evidence: "docs/EVIDENCE_EXCHANGE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence truncation metadata validation status is dashboard-visible", ok: evidenceExchangeDocs.includes("dashboard summary exposes") && evidenceExchangeDocs.includes("`truncation_metadata_status`") && architecture.includes("truncation metadata validation status") && readText("src/lib/evidence-exchange.ts").includes("truncation_metadata_status: built.validation.truncation_metadata_status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence completeness gate is documented and implemented", ok: evidenceExchangeDocs.includes("evidence completeness-check --strict") && evidenceExchangeDocs.includes("all_collections_complete_and_exact") && readText("src/lib/evidence-exchange.ts").includes("checkEvidenceExchangeCompleteness") && readText("src/cli.ts").includes("sub === \"completeness-check\""), evidence: "docs/EVIDENCE_EXCHANGE.md/src/lib/evidence-exchange.ts/src/cli.ts" },
    { name: "Evidence completeness status is dashboard-visible", ok: evidenceExchangeDocs.includes("dashboard summary exposes completeness policy") && evidenceExchangeDocs.includes("and status") && architecture.toLowerCase().includes("evidence completeness status") && readText("src/lib/evidence-exchange.ts").includes("completeness_status: completeness.status") && readText("src/lib/panel-data.ts").includes("completeness: preview.completeness"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence payload byte budget truth is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("exact_utf8_json_bytes_with_80_percent_warning") && evidenceExchangeDocs.includes("payload_byte_status") && architecture.toLowerCase().includes("payload byte") && architecture.toLowerCase().includes("budget, utilization") && readText("src/lib/evidence-exchange.ts").includes("evidenceExchangeByteBudget") && readText("src/lib/panel-data.ts").includes("byte_budget: preview.byte_budget"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence raw-file preflight is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("stat_before_read_with_2mb_limit") && evidenceExchangeDocs.includes("before JSON parsing") && architecture.toLowerCase().includes("raw-file byte preflight") && readText("src/lib/evidence-exchange.ts").includes("EVIDENCE_EXCHANGE_IMPORT_PREFLIGHT_CAPABILITY") && readText("src/lib/panel-data.ts").includes("import_preflight_capability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence import readiness plan is documented and dashboard-visible", ok: EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY.policy === "validated_target_digest_and_count_delta_approval_plan" && EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY.mode === "read_only_approval_plan" && EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY.target_read_performed === false && EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY.comparison_performed === false && EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY.payload_exposed === false && EVIDENCE_EXCHANGE_IMPORT_READINESS_CAPABILITY.writes_allowed === false && evidenceExchangeDocs.includes("validated_target_digest_and_count_delta_approval_plan") && architecture.includes("import-readiness capability") && readText("src/lib/evidence-exchange.ts").includes("planEvidenceExchangeImport") && readText("src/lib/panel-data.ts").includes("import_readiness_capability") && !readText("src/cli.ts").includes("real_evidence_import_requires_approval_and_" + "is_not_implemented"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts/src/cli.ts" },
    { name: "Evidence target path safety is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("realpath_contained_no_symlinks") && evidenceExchangeDocs.includes("single_lstat_with_enoent_only_missing_truth") && architecture.toLowerCase().includes("target path safety") && readText("src/lib/evidence-exchange.ts").includes("inspectTargetPathSafety") && !readText("src/lib/evidence-exchange.ts").includes("fs.existsSync") && readText("src/lib/panel-data.ts").includes("target_path_capability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence single-handle file inspection is documented and dashboard-visible", ok: EVIDENCE_EXCHANGE_CONTRACT.file_handle_close_failure_policy === "structured_fail_closed_no_throw" && EVIDENCE_EXCHANGE_CONTRACT.file_handle_close_failure_reason === "close_failed" && EVIDENCE_EXCHANGE_FILE_HANDLE_CAPABILITY.close_failure_policy === "structured_fail_closed_no_throw" && EVIDENCE_EXCHANGE_FILE_HANDLE_CAPABILITY.close_failure_reason === "close_failed" && evidenceExchangeDocs.includes("single_fd_fstat_read_with_post_open_path_recheck") && evidenceExchangeDocs.includes("structured_fail_closed_no_throw") && evidenceExchangeDocs.includes("import_target_close_failed") && architecture.toLowerCase().includes("single-handle file inspection") && architecture.includes("close_failed") && readText("src/lib/evidence-exchange.ts").includes("inspectAndReadEvidenceTarget") && readText("src/lib/evidence-exchange.ts").includes("target_close_succeeded") && readText("src/lib/panel-data.ts").includes("file_handle_capability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence strict schema shape is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("allowlisted_keys_and_fixed_safety_policy_values") && evidenceExchangeDocs.includes("schema_shape_status") && architecture.toLowerCase().includes("strict schema shape") && readText("src/lib/evidence-exchange.ts").includes("validateSchemaShape") && readText("src/lib/evidence-exchange.ts").includes("schema_shape_status: built.validation.schema_shape_status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence record values are documented and dashboard-visible", ok: evidenceExchangeDocs.includes("required_fields_types_enums_and_timestamps") && evidenceExchangeDocs.includes("record_validation_status") && architecture.toLowerCase().includes("record value validation") && readText("src/lib/evidence-exchange.ts").includes("RECORD_FIELD_RULES") && readText("src/lib/evidence-exchange.ts").includes("record_validation_status: built.validation.record_validation_status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence payload complexity guard is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("iterative_max_depth_32_max_nodes_50000") && evidenceExchangeDocs.includes("serialization_performed: false") && architecture.toLowerCase().includes("payload complexity guard") && readText("src/lib/evidence-exchange.ts").includes("inspectPayloadComplexityAndSafety") && readText("src/lib/evidence-exchange.ts").includes("complexity_status: built.validation.complexity.status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence digest availability is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("explicit_exact_and_content_digest_availability") && evidenceExchangeDocs.includes("digest_availability") && architecture.toLowerCase().includes("digest availability") && readText("src/lib/evidence-exchange.ts").includes("digestAvailability") && readText("src/lib/panel-data.ts").includes("digest_availability: preview.digest_availability"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts/src/lib/panel-data.ts" },
    { name: "Evidence generated_at time truth is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("iso_timestamp_with_5_minute_future_skew_limit") && evidenceExchangeDocs.includes("generated_at_status") && architecture.toLowerCase().includes("generated_at time truth") && readText("src/lib/evidence-exchange.ts").includes("validateGeneratedAt") && readText("src/lib/evidence-exchange.ts").includes("generated_at_status: built.validation.generated_at.status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence temporal consistency is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("generated_at_not_before_valid_record_timestamps") && evidenceExchangeDocs.includes("temporal_consistency_status") && architecture.toLowerCase().includes("temporal consistency") && readText("src/lib/evidence-exchange.ts").includes("validateTemporalConsistency") && readText("src/lib/evidence-exchange.ts").includes("temporal_consistency_status: built.validation.temporal_consistency.status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence collection ordering is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("deterministic_per_collection_visible_field_order") && evidenceExchangeDocs.includes("collection_ordering_status") && architecture.toLowerCase().includes("collection ordering") && readText("src/lib/evidence-exchange.ts").includes("validateCollectionOrdering") && readText("src/lib/evidence-exchange.ts").includes("collection_ordering_status: built.validation.collection_ordering.status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence duplicate-record truth is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("exact_canonical_record_identity_counts_only") && evidenceExchangeDocs.includes("duplicate_record_status") && architecture.toLowerCase().includes("duplicate-record truth") && readText("src/lib/evidence-exchange.ts").includes("validateDuplicateRecords") && readText("src/lib/evidence-exchange.ts").includes("duplicate_record_status: built.validation.duplicate_records.status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence validation findings are bounded and dashboard-visible", ok: evidenceExchangeDocs.includes("bounded_first_200_with_total_count") && evidenceExchangeDocs.includes("validation_findings_truncated") && architecture.toLowerCase().includes("validation finding budget") && readText("src/lib/evidence-exchange.ts").includes("createFindingCollector") && readText("src/lib/evidence-exchange.ts").includes("validation_findings_truncated: built.validation.finding_budget.findings_truncated"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence validation phase execution is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("explicit_executed_skipped_with_dependency_reason") && evidenceExchangeDocs.includes("validation_phase_skip_reasons") && architecture.toLowerCase().includes("validation phase execution") && readText("src/lib/evidence-exchange.ts").includes("validationPhaseExecution") && readText("src/lib/evidence-exchange.ts").includes("validation_phase_execution_status: built.validation.phase_execution.status"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Evidence validation finding attribution is documented and dashboard-visible", ok: evidenceExchangeDocs.includes("counts_only_by_validation_phase") && evidenceExchangeDocs.includes("validation_finding_phase_counts") && architecture.toLowerCase().includes("finding attribution") && readText("src/lib/evidence-exchange.ts").includes("withFindingPhase") && readText("src/lib/evidence-exchange.ts").includes("validation_finding_phase_counts: Object.entries"), evidence: "docs/EVIDENCE_EXCHANGE.md/docs/ARCHITECTURE.md/src/lib/evidence-exchange.ts" },
    { name: "Bounded local worker smoke contract is documented and implemented", ok: WORKER_ENTRYPOINT_INSPECTION_CONTRACT.policy === "fixed_worker_entrypoint_path_metadata_scan" && WORKER_ENTRYPOINT_INSPECTION_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && WORKER_ENTRYPOINT_INSPECTION_CONTRACT.payload_exposed === false && workerDocs.includes("single_bounded_local_read_only_task") && workerDocs.includes("bounded_project_contained_single_handle_worker_package_json") && workerDocs.includes("fixed_worker_entrypoint_path_metadata_scan") && workerDocs.includes("worker-check --strict") && workerDocs.includes("no workload") && architecture.includes("src/worker.ts") && packageJson.includes("\"worker:smoke\"") && readText("src/lib/operations.ts").includes("entrypoint_inspection") && readText("src/worker.ts").includes("inspectWorkerPackage") && exists("src/worker.ts"), evidence: "docs/WORKER.md/docs/ARCHITECTURE.md/package.json/src/worker.ts/src/lib/operations.ts" },
    { name: "Local skill readiness is bounded and external-refresh-safe", ok: CLAUDE_SKILL_INSPECTION_CONTRACT.policy === "bounded_project_skill_readiness_scan" && CLAUDE_SKILL_INSPECTION_CONTRACT.max_skill_bytes === 4000 && CLAUDE_SKILL_INSPECTION_CONTRACT.payload_exposed === false && CLAUDE_SKILL_INSPECTION_CONTRACT.writes_allowed === false && EXTERNAL_SKILL_REFRESH_INSPECTION_CONTRACT.policy === "bounded_local_skill_readiness_without_external_fetch_or_install" && EXTERNAL_SKILL_REFRESH_INSPECTION_CONTRACT.external_fetch_allowed === false && EXTERNAL_SKILL_REFRESH_INSPECTION_CONTRACT.install_allowed === false && externalSkillInspection.status === "dry_run_only" && externalSkillInspection.local_readiness_status === "safe_to_execute" && externalSkillInspection.unready_skill_count === 0 && externalSkillInspection.scan_complete === true && externalSkillInspection.external_fetch_performed === false && externalSkillInspection.install_performed === false && cliDocs.includes("bounded_local_skill_readiness_without_external_fetch_or_install") && architecture.includes("Local skill readiness inspection") && readText("docs/recipes/ui-ux-skill-radar.md").includes("external-skills-refresh") && readText("src/lib/operations.ts").includes("local_readiness_status"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/docs/recipes/ui-ux-skill-radar.md/src/lib/repo-inspection.ts/src/lib/operations.ts" },
    { name: "Smart suggestions and opportunity radar require complete source truth", ok: SMART_SUGGESTION_INSPECTION_CONTRACT.policy === "bounded_local_advisory_from_explicit_source_truth" && SMART_SUGGESTION_INSPECTION_CONTRACT.source_count === 7 && SMART_SUGGESTION_INSPECTION_CONTRACT.max_suggestions === 7 && SMART_SUGGESTION_INSPECTION_CONTRACT.incomplete_source_policy === "manual_verification_required" && SMART_SUGGESTION_INSPECTION_CONTRACT.payload_exposed === false && SMART_SUGGESTION_INSPECTION_CONTRACT.external_fetch_allowed === false && SMART_SUGGESTION_INSPECTION_CONTRACT.writes_allowed === false && OPPORTUNITY_RADAR_INSPECTION_CONTRACT.policy === "bounded_local_opportunities_from_smart_suggestion_truth" && OPPORTUNITY_RADAR_INSPECTION_CONTRACT.source_policy === SMART_SUGGESTION_INSPECTION_CONTRACT.policy && OPPORTUNITY_RADAR_INSPECTION_CONTRACT.external_fetch_allowed === false && opportunityRadar.status === "safe_to_execute" && opportunityRadar.scan_complete === true && opportunityRadar.incomplete_sources.length === 0 && opportunityRadar.external_fetch_performed === false && opportunityRadar.writes_performed === false && cliDocs.includes("bounded_local_advisory_from_explicit_source_truth") && architecture.includes("Smart suggestion source truth") && readText("src/lib/operations.ts").includes("smart_suggestion_source_incomplete"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/operations.ts" },
    { name: "Plan-only commands require complete source truth", ok: PLAN_SOURCE_TRUTH_CONTRACT.policy === "plan_status_requires_complete_source_truth" && PLAN_SOURCE_TRUTH_CONTRACT.incomplete_source_status === "manual_verification_required" && PLAN_SOURCE_TRUTH_CONTRACT.known_finding_plan_status === "dry_run_only" && PLAN_SOURCE_TRUTH_CONTRACT.payload_exposed === false && PLAN_SOURCE_TRUTH_CONTRACT.writes_allowed === false && cliDocs.includes("plan_status_requires_complete_source_truth") && architecture.includes("Plan source truth") && readText("src/lib/action-plans.ts").includes("drift_fix_source_truth_incomplete") && readText("src/lib/action-plans.ts").includes("locale_sync_source_truth_incomplete") && readText("src/lib/action-plans.ts").includes("n8n_plan_source_truth_incomplete") && readText("src/lib/action-plans.ts").includes("inspectWorker(options)") && readText("src/lib/action-plans.ts").includes("source_scan_complete"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/action-plans.ts" },
    { name: "Action-plan user inputs are bounded and payload-free", ok: ACTION_PLAN_USER_INPUT_CONTRACT.policy === "bounded_complete_user_input_classification_with_payload_free_metadata" && ACTION_PLAN_USER_INPUT_CONTRACT.max_input_bytes === 4_096 && ACTION_PLAN_USER_INPUT_CONTRACT.oversized_input_status === "manual_verification_required" && ACTION_PLAN_USER_INPUT_CONTRACT.raw_goal_exposed === false && ACTION_PLAN_USER_INPUT_CONTRACT.raw_target_exposed === false && ACTION_PLAN_USER_INPUT_CONTRACT.payload_exposed === false && ACTION_PLAN_USER_INPUT_CONTRACT.writes_allowed === false && cliDocs.includes("bounded_complete_user_input_classification_with_payload_free_metadata") && architecture.includes("Action-plan user inputs") && readText("src/lib/action-plans.ts").includes("inspectActionPlanUserInput") && !readText("src/lib/action-plans.ts").includes("goal: normalizedGoal") && !readText("src/lib/action-plans.ts").includes("target: String(target"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/action-plans.ts" },
    { name: "Read-only cross-platform privilege detection is documented and implemented", ok: adminDocs.includes("windows_principal_administrator_role_read_only") && adminDocs.includes("posix_getuid") && adminDocs.includes("never requests elevation") && architecture.includes("admin-check") && readText("src/lib/operations.ts").includes("WINDOWS_PRIVILEGE_PROBE"), evidence: "docs/ADMIN.md/docs/ARCHITECTURE.md/src/lib/operations.ts" },
    { name: "Interactive mistake capture contract is documented and implemented", ok: INTERACTIVE_MISTAKE_CONTRACT.close_before_safe_result === true && INTERACTIVE_MISTAKE_CONTRACT.close_failure_policy === "payload_free_manual_verification_no_write" && INTERACTIVE_MISTAKE_CONTRACT.close_failure_blocker === "interactive_prompt_close_failed" && INTERACTIVE_MISTAKE_CONTRACT.payload_exposed_on_failure === false && memoryDocs.includes("tty_only_validated_confirmation_before_write") && memoryDocs.includes("real TTY") && memoryDocs.includes("explicit confirmation") && memoryDocs.includes("interactive_prompt_close_failed") && cliDocs.includes("payload_free_manual_verification_no_write") && architecture.includes("Prompt close failure") && readText("src/lib/interactive-memory.ts").includes("prompt_close_status: \"failed\"") && readText("src/cli.ts").includes("interactive_and_inline_inputs_cannot_be_combined") && !readText("src/cli.ts").includes("Interactive prompting is not implemented"), evidence: "docs/MEMORY.md/docs/CLI.md/docs/ARCHITECTURE.md/src/lib/interactive-memory.ts/src/cli.ts" },
    {
      name: "Memory registry appends are bounded, contained, and safe",
      ok: MEMORY_REGISTRY_APPEND_CONTRACT.policy === "fixed_project_contained_create_or_single_handle_memory_registry_append"
        && MEMORY_REGISTRY_APPEND_CONTRACT.max_record_bytes === 1_000_000
        && MEMORY_REGISTRY_APPEND_CONTRACT.max_registry_bytes === 5_000_000
        && MEMORY_REGISTRY_APPEND_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only"
        && MEMORY_REGISTRY_APPEND_CONTRACT.concurrent_write_policy === "bounded_fixed_create_only_lock_serialized_create_or_append"
        && MEMORY_REGISTRY_APPEND_CONTRACT.max_write_lock_attempts === 100
        && MEMORY_REGISTRY_APPEND_CONTRACT.transient_lock_observation_policy === "bounded_retry_on_existing_lock_inspection_race"
        && MEMORY_REGISTRY_APPEND_CONTRACT.post_release_success_policy === "released_identity_absent_or_safe_successor"
        && MEMORY_REGISTRY_APPEND_CONTRACT.stale_write_lock_reclamation_allowed === false
        && MEMORY_REGISTRY_APPEND_CONTRACT.atomic_create_link === true
        && MEMORY_REGISTRY_APPEND_CONTRACT.first_create_temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match"
        && MEMORY_REGISTRY_APPEND_CONTRACT.first_create_identity_safe_temp_cleanup === true
        && MEMORY_REGISTRY_APPEND_CONTRACT.first_create_post_publish_identity_policy === "temporary_and_registry_dev_ino_match"
        && MEMORY_REGISTRY_APPEND_CONTRACT.single_append_handle === true
        && MEMORY_REGISTRY_APPEND_CONTRACT.close_failure_error === "memory_registry_append_blocked:file_close_failed"
        && MEMORY_REGISTRY_APPEND_CONTRACT.payload_exposed_on_failure === false
        && memoryDocs.includes("fixed_project_contained_create_or_single_handle_memory_registry_append")
        && memoryDocs.includes("bounded_fixed_create_only_lock_serialized_create_or_append")
        && memoryDocs.includes("bounded_retry_on_existing_lock_inspection_race")
        && memoryDocs.includes("released_identity_absent_or_safe_successor")
        && memoryDocs.includes("write_handle_and_temporary_path_dev_ino_match")
        && memoryDocs.includes("temporary_and_registry_dev_ino_match")
        && memoryDocs.includes("memory_registry_append_blocked:file_close_failed")
        && architecture.includes("Memory registry append")
        && architecture.includes("memory_registry_append_blocked:file_close_failed")
        && readText("src/lib/memory.ts").includes("confirmMemoryRegistryWriteLockReleased")
        && readText("src/lib/memory.ts").includes("MEMORY_REGISTRY_APPEND_CONTRACT.close_failure_error")
        && readText("src/lib/memory.ts").includes("withMemoryRegistryWriteLock")
        && readText("src/lib/memory.ts").includes("unlinkIfSameFileIdentity")
        && readText("src/lib/memory.ts").includes("sameFileIdentity")
        && !readText("src/lib/memory.ts").includes("appendFileSync"),
      evidence: "docs/MEMORY.md/docs/ARCHITECTURE.md/src/lib/memory.ts"
    },
    { name: "Memory registry scan is bounded and raw-invalid-line-safe", ok: MEMORY_REGISTRY_SCAN_CONTRACT.policy === "bounded_single_handle_jsonl_without_invalid_raw_line_exposure" && MEMORY_REGISTRY_SCAN_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && MEMORY_REGISTRY_SCAN_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && MEMORY_REGISTRY_SCAN_CONTRACT.close_failure_blocker === "memory_registry_file_close_failed" && MEMORY_REGISTRY_SCAN_CONTRACT.payload_exposed_on_failure === false && memoryDocs.includes("memory_registry_file_close_failed") && memoryDocs.includes("invalid raw line") && architecture.includes("memory_registry_file_close_failed") && readText("src/lib/memory.ts").includes("MEMORY_REGISTRY_SCAN_CONTRACT.close_failure_blocker") && !readText("src/lib/memory.ts").includes("fs.existsSync") && readText("src/cli.ts").includes("matching_mistakes_exact"), evidence: "docs/MEMORY.md/docs/ARCHITECTURE.md/src/lib/memory.ts/src/cli.ts" },
    { name: "n8n import target inspection is bounded and documented", ok: N8N_IMPORT_INSPECTION_CONTRACT.policy === "realpath_contained_single_handle_max_1mb_json" && N8N_IMPORT_INSPECTION_CONTRACT.post_read_path_recheck === true && N8N_IMPORT_INSPECTION_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && N8N_IMPORT_INSPECTION_CONTRACT.close_failure_blocker === "workflow_target_close_failed" && N8N_IMPORT_INSPECTION_CONTRACT.workflow_summary_policy === "counts_and_boolean_metadata_without_raw_workflow_fields" && N8N_IMPORT_INSPECTION_CONTRACT.raw_workflow_name_exposed === false && N8N_IMPORT_INSPECTION_CONTRACT.payload_exposed_on_failure === false && n8nDocs.includes("1,000,000") && n8nDocs.includes("counts_and_boolean_metadata_without_raw_workflow_fields") && n8nDocs.includes("structured_fail_closed_no_throw") && n8nDocs.includes("workflow_target_close_failed") && architecture.includes("post-read path identity recheck") && architecture.includes("raw workflow name") && architecture.includes("workflow_target_close_failed") && readText("src/lib/action-plans.ts").includes("inspectN8nWorkflowTarget") && readText("src/lib/action-plans.ts").includes("post_read_path_recheck_performed") && readText("src/lib/action-plans.ts").includes("workflow_target_changed_after_read") && readText("src/lib/action-plans.ts").includes("raw_name_exposed: false") && readText("src/lib/action-plans.ts").includes("target_close_succeeded"), evidence: "docs/recipes/n8n-background.md/docs/ARCHITECTURE.md/src/lib/action-plans.ts" },
    { name: "Archive inventory is bounded and exactness-aware", ok: ARCHIVE_INVENTORY_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && ARCHIVE_INVENTORY_CONTRACT.directory_close_failure_blocker === "archive_inventory_directory_close_failed" && ARCHIVE_INVENTORY_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("bounded_directory_iterator_with_explicit_exactness") && cliDocs.includes("candidate_count_exact") && cliDocs.includes("root_inspection") && cliDocs.includes("archive_inventory_directory_close_failed") && architecture.includes("archive-old") && architecture.includes("Archive inventory root") && architecture.includes("archive_inventory_directory_close_failed") && readText("src/lib/action-plans.ts").includes("ARCHIVE_INVENTORY_CONTRACT") && readText("src/lib/action-plans.ts").includes("root_inspection: rootInspection") && readText("src/lib/action-plans.ts").includes("scan_truncated"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/action-plans.ts" },
    { name: "Ledger appends are fixed, bounded, and single-handle", ok: LEDGER_APPEND_CONTRACT.policy === "fixed_allowlisted_project_contained_single_handle_append" && LEDGER_APPEND_CONTRACT.allowed_file_count === 6 && LEDGER_APPEND_CONTRACT.max_record_bytes === 1_000_000 && LEDGER_APPEND_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && LEDGER_APPEND_CONTRACT.concurrent_mutation_policy === "bounded_fixed_create_only_lock_serialized_ledger_mutations" && LEDGER_APPEND_CONTRACT.max_mutation_lock_attempts === 100 && LEDGER_APPEND_CONTRACT.stale_mutation_lock_reclamation_allowed === false && LEDGER_APPEND_CONTRACT.single_append_handle === true && LEDGER_APPEND_CONTRACT.close_failure_error === "ledger_append_blocked:file_close_failed" && LEDGER_APPEND_CONTRACT.payload_exposed_on_failure === false && memoryDocs.includes("fixed_allowlisted_project_contained_single_handle_append") && memoryDocs.includes("bounded_fixed_create_only_lock_serialized_ledger_mutations") && memoryDocs.includes("ledger_append_blocked:file_close_failed") && architecture.includes("Ledger append") && architecture.includes("ledger_append_blocked:file_close_failed") && readText("src/lib/ledger.ts").includes("LEDGER_APPEND_CONTRACT.close_failure_error") && readText("src/lib/ledger.ts").includes("withLedgerMutationLock") && readText("src/lib/ledger-lock.ts").includes("withLedgerMutationLock") && !readText("src/lib/ledger.ts").includes("appendFileSync"), evidence: "docs/MEMORY.md/docs/ARCHITECTURE.md/src/lib/ledger.ts/src/lib/ledger-lock.ts" },
    { name: "Raw evidence writes are bounded, contained, and create-only", ok: RAW_EVIDENCE_WRITE_CONTRACT.policy === "bounded_project_contained_atomic_create_only_redacted_raw_evidence" && RAW_EVIDENCE_WRITE_CONTRACT.max_file_bytes === 5_000_000 && RAW_EVIDENCE_WRITE_CONTRACT.max_kind_bytes === 256 && RAW_EVIDENCE_WRITE_CONTRACT.kind_policy === "bounded_redacted_before_envelope_and_filename" && RAW_EVIDENCE_WRITE_CONTRACT.raw_kind_exposed === false && RAW_EVIDENCE_WRITE_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && RAW_EVIDENCE_WRITE_CONTRACT.temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match" && RAW_EVIDENCE_WRITE_CONTRACT.identity_safe_temp_cleanup === true && RAW_EVIDENCE_WRITE_CONTRACT.post_publish_identity_policy === "temporary_and_target_dev_ino_match" && RAW_EVIDENCE_WRITE_CONTRACT.atomic_create_link === true && RAW_EVIDENCE_WRITE_CONTRACT.overwrite_allowed === false && RAW_EVIDENCE_WRITE_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("bounded_project_contained_atomic_create_only_redacted_raw_evidence") && cliDocs.includes("bounded_redacted_before_envelope_and_filename") && cliDocs.includes("write_handle_and_temporary_path_dev_ino_match") && cliDocs.includes("temporary_and_target_dev_ino_match") && architecture.includes("Raw evidence write") && readText("src/lib/evidence.ts").includes("safeEvidenceKind") && readText("src/lib/evidence.ts").includes("fs.linkSync") && readText("src/lib/evidence.ts").includes("unlinkIfSameFileIdentity") && readText("src/lib/evidence.ts").includes("sameFileIdentity") && readText("src/lib/evidence.ts").includes("content_exceeds_byte_limit"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/evidence.ts" },
    { name: "Public evidence writes are fixed, bounded, and atomic", ok: PUBLIC_EVIDENCE_WRITE_CONTRACT.policy === "bounded_fixed_project_contained_atomic_public_evidence_replace" && PUBLIC_EVIDENCE_WRITE_CONTRACT.allowed_file_count === 1 && PUBLIC_EVIDENCE_WRITE_CONTRACT.max_file_bytes === 1_000_000 && PUBLIC_EVIDENCE_WRITE_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && PUBLIC_EVIDENCE_WRITE_CONTRACT.concurrent_write_policy === "last_writer_wins_rechecked_transient_atomic_replace_retry" && PUBLIC_EVIDENCE_WRITE_CONTRACT.max_atomic_replace_attempts === 20 && PUBLIC_EVIDENCE_WRITE_CONTRACT.temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match_before_each_replace_attempt" && PUBLIC_EVIDENCE_WRITE_CONTRACT.identity_safe_temp_cleanup === true && PUBLIC_EVIDENCE_WRITE_CONTRACT.atomic_replace === true && PUBLIC_EVIDENCE_WRITE_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("bounded_fixed_project_contained_atomic_public_evidence_replace") && cliDocs.includes("last_writer_wins_rechecked_transient_atomic_replace_retry") && cliDocs.includes("write_handle_and_temporary_path_dev_ino_match_before_each_replace_attempt") && architecture.includes("Public evidence write") && readText("src/lib/evidence.ts").includes("PUBLIC_EVIDENCE_FILES") && readText("src/lib/evidence.ts").includes("TRANSIENT_ATOMIC_REPLACE_ERROR_CODES") && readText("src/lib/evidence.ts").includes("unlinkIfSameFileIdentity") && readText("src/lib/evidence.ts").includes("fs.renameSync"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/evidence.ts" },
    { name: "Ledger safety scan is bounded and repair-gated", ok: LEDGER_SAFETY_SCAN_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && LEDGER_SAFETY_SCAN_CONTRACT.close_failure_blocker === "ledger_file_close_failed" && LEDGER_SAFETY_SCAN_CONTRACT.directory_close_failure_blocker === "ledger_directory_close_failed" && LEDGER_SAFETY_SCAN_CONTRACT.payload_exposed_on_failure === false && memoryDocs.includes("bounded_single_handle_jsonl_scan_with_true_finding_count") && memoryDocs.includes("scan_complete") && memoryDocs.includes("ledger_file_close_failed") && memoryDocs.includes("ledger_directory_close_failed") && cliDocs.includes("10 MB") && architecture.includes("ledger-safety-check") && architecture.includes("ledger_file_close_failed") && architecture.includes("ledger_directory_close_failed") && readText("src/lib/ledger-safety.ts").includes("LEDGER_SAFETY_SCAN_CONTRACT.close_failure_blocker") && readText("src/lib/ledger-safety.ts").includes("LEDGER_SAFETY_SCAN_CONTRACT.directory_close_failure_blocker") && readText("src/lib/ledger-safety.ts").includes("repair_blocked_by_incomplete_scan"), evidence: "docs/MEMORY.md/docs/CLI.md/docs/ARCHITECTURE.md/src/lib/ledger-safety.ts" },
    { name: "Ledger repair writes are contained, backed up, and atomic", ok: LEDGER_REPAIR_WRITE_CONTRACT.policy === "bounded_project_contained_atomic_backup_then_replace" && LEDGER_REPAIR_WRITE_CONTRACT.max_file_bytes === 10_000_000 && LEDGER_REPAIR_WRITE_CONTRACT.parent_directory_creation_policy === "one_segment_at_a_time_with_path_recheck" && LEDGER_REPAIR_WRITE_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && LEDGER_REPAIR_WRITE_CONTRACT.concurrent_mutation_policy === "bounded_fixed_create_only_lock_serialized_ledger_mutations" && LEDGER_REPAIR_WRITE_CONTRACT.max_mutation_lock_attempts === 100 && LEDGER_REPAIR_WRITE_CONTRACT.stale_mutation_lock_reclamation_allowed === false && LEDGER_REPAIR_WRITE_CONTRACT.backup_create_only === true && LEDGER_REPAIR_WRITE_CONTRACT.atomic_create_link === true && LEDGER_REPAIR_WRITE_CONTRACT.temporary_source_identity_policy === "write_handle_and_temporary_path_dev_ino_match" && LEDGER_REPAIR_WRITE_CONTRACT.identity_safe_temp_cleanup === true && LEDGER_REPAIR_WRITE_CONTRACT.backup_post_publish_identity_policy === "temporary_and_backup_dev_ino_match" && LEDGER_REPAIR_WRITE_CONTRACT.atomic_replace === true && LEDGER_REPAIR_WRITE_CONTRACT.replacement_post_publish_identity_policy === "temporary_and_live_ledger_dev_ino_match" && LEDGER_REPAIR_WRITE_CONTRACT.original_backup_required === true && LEDGER_REPAIR_WRITE_CONTRACT.payload_exposed_on_failure === false && LEDGER_REPAIR_WRITE_CONTRACT.writes_outside_project_allowed === false && memoryDocs.includes("bounded_project_contained_atomic_backup_then_replace") && memoryDocs.includes("bounded_fixed_create_only_lock_serialized_ledger_mutations") && memoryDocs.includes("write_handle_and_temporary_path_dev_ino_match") && memoryDocs.includes("temporary_and_backup_dev_ino_match") && memoryDocs.includes("temporary_and_live_ledger_dev_ino_match") && cliDocs.includes("bounded_project_contained_atomic_backup_then_replace") && architecture.includes("Ledger repair write") && readText("src/lib/ledger-safety.ts").includes("atomicCreateBackup") && readText("src/lib/ledger-safety.ts").includes("atomicReplaceLedger") && readText("src/lib/ledger-safety.ts").includes("unlinkIfSameFileIdentity") && readText("src/lib/ledger-safety.ts").includes("sameFileIdentity") && readText("src/lib/ledger-safety.ts").includes("withLedgerMutationLock") && !readText("src/lib/ledger-safety.ts").includes("fs.copyFileSync") && !readText("src/lib/ledger-safety.ts").includes("fs.writeFileSync(plan.fullPath"), evidence: "docs/MEMORY.md/docs/CLI.md/docs/ARCHITECTURE.md/src/lib/ledger-safety.ts/src/lib/ledger-lock.ts" },
    { name: "Latest evidence lookup is bounded and exactness-aware", ok: LATEST_EVIDENCE_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && LATEST_EVIDENCE_CONTRACT.directory_close_failure_blocker === "raw_evidence_directory_close_failed" && LATEST_EVIDENCE_CONTRACT.file_close_failure_blocker === "latest_evidence_file_close_failed" && LATEST_EVIDENCE_CONTRACT.payload_exposed_on_failure === false && cliDocs.includes("bounded_directory_iterator_latest_mtime_with_prefix_read") && cliDocs.includes("latest_exact") && cliDocs.includes("Latest-evidence root truth") && cliDocs.includes("raw_evidence_directory_close_failed") && cliDocs.includes("latest_evidence_file_close_failed") && architecture.includes("evidence last") && architecture.includes("Latest-evidence inventory root") && architecture.includes("raw_evidence_directory_close_failed") && architecture.includes("latest_evidence_file_close_failed") && readText("src/lib/evidence.ts").includes("LATEST_EVIDENCE_CONTRACT") && readText("src/lib/evidence.ts").includes("root_inspection: rootInspection") && readText("src/lib/evidence.ts").includes("preview_bytes_read"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/evidence.ts" },
    { name: "Repo quality scans are bounded and exactness-aware", ok: REPO_SCAN_CONTRACT.policy === "bounded_realpath_contained_inventory_with_single_handle_text_reads" && REPO_SCAN_CONTRACT.path_metadata_policy === "realpath_contained_symlink_free_path_metadata_only" && REPO_SCAN_CONTRACT.missing_path_ancestor_check === true && REPO_SCAN_CONTRACT.max_total_text_bytes === 20_000_000 && REPO_SCAN_CONTRACT.post_read_path_recheck === true && REPO_SCAN_CONTRACT.metadata_failure_policy === "structured_fail_closed_no_throw" && REPO_SCAN_CONTRACT.directory_close_failure_blocker === "repo_directory_close_failed" && REPO_SCAN_CONTRACT.payload_exposed_on_failure === false && architectureInspection.root_inspection.status === "safe_to_execute" && architectureInspection.root_inspection.payload_exposed === false && cliDocs.includes("Repo inventory root truth") && cliDocs.includes("repo_text_file_close_failed") && cliDocs.includes("repo_directory_close_failed") && architecture.includes("Repo inventory root truth") && architecture.includes("repo_directory_close_failed") && readText("src/lib/repo-scan.ts").includes("root_inspection: rootInspection") && readText("src/lib/repo-scan.ts").includes("repo_text_file_close_failed") && readText("src/lib/repo-scan.ts").includes("REPO_SCAN_CONTRACT.directory_close_failure_blocker"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/repo-scan.ts" },
    { name: "Quality required artifact paths are contained and payload-free", ok: QUALITY_REQUIRED_ARTIFACT_INSPECTION_CONTRACT.policy === "bounded_fixed_quality_required_artifact_path_metadata_scan" && QUALITY_REQUIRED_ARTIFACT_INSPECTION_CONTRACT.required_path_count === 4 && QUALITY_REQUIRED_ARTIFACT_INSPECTION_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && QUALITY_REQUIRED_ARTIFACT_INSPECTION_CONTRACT.payload_exposed === false && qualityRequiredArtifacts.status === "safe_to_execute" && qualityRequiredArtifacts.scan_complete === true && qualityRequiredArtifacts.inspections.length === 4 && cliDocs.includes("bounded_fixed_quality_required_artifact_path_metadata_scan") && architecture.includes("Quality required-artifact path inspection") && readText("src/lib/quality-radar.ts").includes("required_artifacts"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/quality-radar.ts/src/lib/repo-scan.ts" },
    { name: "CLI path presence decisions use contained metadata", ok: REPO_PATH_PRESENCE_CONTRACT.policy === "repo_path_presence_from_contained_metadata_only" && REPO_PATH_PRESENCE_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && REPO_PATH_INSPECTION_CONTRACT.missing_path_ancestor_check === true && REPO_PATH_PRESENCE_CONTRACT.payload_exposed === false && cliPathPresence.status === "safe_to_execute" && cliPathPresence.present === true && cliDocs.toLowerCase().includes("missing-target ancestors") && architecture.toLowerCase().includes("missing-target ancestors") && readText("src/cli.ts").includes("inspectRepoPathPresence") && !readText("src/cli.ts").includes("fs.existsSync"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/cli.ts/src/lib/repo-scan.ts" },
    { name: "Architecture layer paths are contained and payload-free", ok: ARCHITECTURE_PATH_INSPECTION_CONTRACT.policy === "bounded_fixed_architecture_path_metadata_scan" && ARCHITECTURE_PATH_INSPECTION_CONTRACT.required_path_count === 7 && ARCHITECTURE_PATH_INSPECTION_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && ARCHITECTURE_PATH_INSPECTION_CONTRACT.payload_exposed === false && architectureInspection.status === "safe_to_execute" && architectureInspection.scan_complete === true && architectureInspection.path_inspections.length === 7 && cliDocs.includes("bounded_fixed_architecture_path_metadata_scan") && architecture.includes("Architecture layer path inspection") && readText("src/lib/repo-inspection.ts").includes("path_inspections"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/repo-inspection.ts/src/lib/repo-scan.ts" },
    { name: "i18n artifact paths are contained and payload-free", ok: I18N_ARTIFACT_INSPECTION_CONTRACT.policy === "bounded_fixed_i18n_artifact_path_metadata_scan" && I18N_ARTIFACT_INSPECTION_CONTRACT.required_path_count === 2 && I18N_ARTIFACT_INSPECTION_CONTRACT.path_policy === "realpath_contained_symlink_free_path_metadata_only" && I18N_ARTIFACT_INSPECTION_CONTRACT.payload_exposed === false && i18nInspection.status === "safe_to_execute" && i18nInspection.scan_complete === true && i18nInspection.artifact_inspections.length === 2 && cliDocs.includes("bounded_fixed_i18n_artifact_path_metadata_scan") && architecture.includes("i18n artifact path inspection") && readText("src/lib/operations.ts").includes("artifact_inspections"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/operations.ts/src/lib/repo-scan.ts" },
    { name: "Git sync and remote observations are bounded and failure-aware", ok: SYNC_OBSERVATION_CONTRACT.status_policy === "bounded_git_porcelain_v1_z_with_explicit_process_truth" && SYNC_OBSERVATION_CONTRACT.head_policy === "bounded_git_rev_parse_head_with_validated_hash" && cliDocs.includes("bounded_git_porcelain_v1_z_with_explicit_process_truth") && cliDocs.includes("bounded_git_rev_parse_head_with_validated_hash") && cliDocs.includes("changed_files_count_exact") && architecture.includes("Git worktree, remote, and HEAD truth") && readText("src/lib/sync.ts").includes("inspectGitStatus") && readText("src/lib/sync.ts").includes("inspectGitHead") && readText("src/lib/push-readiness.ts").includes("inspectGitRemotes") && readText("src/lib/operations.ts").includes("inspectGitHead"), evidence: "docs/CLI.md/docs/ARCHITECTURE.md/src/lib/sync.ts/src/lib/push-readiness.ts/src/lib/operations.ts" },
    { name: "Package/manifest/README major version agrees", ok: versionContract.failures.length === 0, evidence: "package.json/manifest.json/README.md" },
    { name: "Public claim honesty passes", ok: docsHonesty.status === "safe_to_execute" && docsHonesty.scan_complete === true && docsHonesty.finding_count === 0, evidence: "docs-honesty-check" }
  ];
  if (!quick) {
    checks.push(
      { name: "Current sources evidence exists", ok: exists("docs/evidence/current-sources.md"), evidence: "docs/evidence/current-sources.md" },
      { name: "V28 research evidence exists", ok: exists("docs/evidence/v28-web-research.md"), evidence: "docs/evidence/v28-web-research.md" },
      { name: "Reference radar state exists", ok: exists(".pala/state/reference-radar-state.json"), evidence: ".pala/state/reference-radar-state.json" },
      { name: "Workflow contracts pass", ok: workflowContract.failures.length === 0 && workflowContract.scan_complete === true, evidence: "workflow-check" },
      { name: "Durable autonomous handoff exists", ok: exists("docs/evidence/autonomous-improvement-handoff.md"), evidence: "docs/evidence/autonomous-improvement-handoff.md" }
    );
  }
  const textRead = textContext.summary();
  const blockers = [...new Set([
    ...textRead.blockers,
    ...(databasePath.status === "safe_to_execute" && databasePath.exists === true ? [] : [`database_path:${databasePath.blocker || "missing"}`]),
    ...(publicReadiness.scan_complete ? [] : publicReadiness.blockers.map((blocker) => `public_readiness:${blocker}`)),
    ...(qualityRequiredArtifacts.scan_complete ? [] : qualityRequiredArtifacts.blockers.map((blocker) => `quality_required_artifacts:${blocker}`)),
    ...(externalSkillInspection.scan_complete ? [] : externalSkillInspection.blockers.map((blocker) => `external_skills:${blocker}`)),
    ...(opportunityRadar.scan_complete ? [] : opportunityRadar.blockers.map((blocker) => `opportunity_radar:${blocker}`))
  ])];
  const scanComplete = textRead.scan_complete && databasePath.status === "safe_to_execute" && databasePath.exists === true && publicReadiness.scan_complete === true && qualityRequiredArtifacts.scan_complete === true && externalSkillInspection.scan_complete === true && opportunityRadar.scan_complete === true;
  checks.push({
    name: "Drift contract text reads are bounded and complete",
    ok: textRead.policy === "bounded_cached_contract_text_reads_with_shared_budget"
      && textRead.max_file_bytes <= DRIFT_TEXT_READ_CONTRACT.max_file_bytes
      && textRead.max_total_text_bytes <= DRIFT_TEXT_READ_CONTRACT.max_total_text_bytes
      && textRead.scan_complete === true
      && textRead.payload_exposed === false
      && textRead.writes_performed === false,
    evidence: "drift source reads"
  });
  const failures = checks.filter((check) => !check.ok);
  return {
    status: failures.length === 0 ? "safe_to_execute" : "manual_verification_required",
    quick,
    checks,
    failures,
    scan_complete: scanComplete,
    blockers,
    text_read: textRead,
    payload_exposed: false,
    writes_performed: false,
    version_contract: versionContract,
    workflow_contract: workflowContract,
    public_readiness: publicReadiness,
    database_path_inspection: databasePath,
    architecture_inspection: architectureInspection,
    i18n_inspection: i18nInspection,
    external_skill_inspection: externalSkillInspection,
    opportunity_radar: opportunityRadar,
    runtime_project_assets: runtimeProjectAssets,
    quality_required_artifacts: qualityRequiredArtifacts,
    note: "Semantic drift compares positioning, versions, strict-mode, read-only dashboard, persistence, MCP, public-readiness, workflow, and evidence contracts."
  };
}
